---
# tasks file for common
- name: Validate source distribution and major version
  ansible.builtin.fail:
    msg: "The system must be CentOS/Oracle/Alma/Rocky Linux 7 or 8"
  when:
    - ansible_distribution not in common_supported_distribution
    - ansible_distribution_major_version in common_supported_major_version

- name: Register output of 'yum repolist'
  ansible.builtin.shell: >
    export PATH={{ analysis_os_path }};
    set -o pipefail;
    yum repolist all --verbose | grep Repo-baseurl | grep -v convert2rhel
  args:
    executable: /bin/bash
  register: yum_repolist_for_baseurl
  changed_when: yum_repolist_for_baseurl.rc != 0

- name: Set analysis_convert2rhel_repo_type to 'satellite'
  ansible.builtin.set_fact:
    analysis_convert2rhel_repo_type: 'satellite'
  when: yum_repolist_for_baseurl.stdout | regex_search('\/pulp\/content\/' + rhsm_org | string + '\/' + rhsm_activation_key_pre_convert | string )

- name: Patch repositories if dealing with CentOS 7.
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version | int == 7 and analysis_convert2rhel_repo_type is not 'satellite'
  block:
    - name: Comment mirrorlist in all repos.
      ansible.builtin.replace:
        path: /etc/yum.repos.d/{{ item }}
        regexp: ^mirrorlist
        replace: "#mirrorlist"
      loop: "{{ common_centos7_repos }}"

    - name: Switch repo to vault.centos.org.
      ansible.builtin.replace:
        path: /etc/yum.repos.d/{{ item }}
        regexp: "#baseurl=http://mirror.centos.org"
        replace: baseurl=https://vault.centos.org
      loop: "{{ common_centos7_repos }}"

- name: Patch repositories if dealing with CentOS 8.
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version | int == 8 and analysis_convert2rhel_repo_type is not 'satellite'
  block:
    - name: Comment mirrorlist in all repos.
      ansible.builtin.replace:
        path: /etc/yum.repos.d/{{ item }}
        regexp: ^mirrorlist
        replace: "#mirrorlist"
      loop: "{{ common_centos8_repos }}"

    - name: Switch repo to vault.centos.org.
      ansible.builtin.replace:
        path: /etc/yum.repos.d/{{ item }}
        regexp: "#baseurl=http://mirror.centos.org"
        replace: baseurl=https://vault.centos.org
      loop: "{{ common_centos8_repos }}"

- name: Setup Convert2RHEL repository
  when: not common_convert2rhel_repo_satellite and analysis_convert2rhel_repo_type is not 'satellite'
  block:
    - name: Download Red Hat GPG key
      ansible.builtin.get_url:
        url:  "{{ common_convert2rhel_repokey_url }}"
        dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release"
        mode: '0644'

    - name: Determinate repofile for target
      ansible.builtin.include_tasks: determinate-repofile.yml

    - name: Add Convert2RHEL yum repository from Red Hat
      ansible.builtin.get_url:
        url: "{{ convert2rhel_repofile_url }}"
        dest: "/etc/yum.repos.d/convert2rhel.repo"
        mode: '0644'

- name: Satellite content host - switch to Convert2RHEL lifecycle environment and content view
  when: analysis_convert2rhel_repo_type == 'satellite'
  redhat.satellite.host:
    name: "{{ ansible_host }}"
    lifecycle_environment: "{{ rhsat_lifecycle_environment }}"
    content_view: "{{ rhsat_content_view }}"

- name: Install Convert2RHEL
  ansible.builtin.package:
    name: convert2rhel
    enablerepo: "{{ common_yum_enable_repos | default(omit) }}"

- name: Create temporary configuration file
  ansible.builtin.tempfile:
    state: file
    prefix: convert2rhel_configfile_
  register: convert2rhel_configfile

- name: Write config into configuration file
  ansible.builtin.template:
    src: configfile.j2
    dest: "{{ convert2rhel_configfile.path }}"
    mode: '0600'
  when: not common_convert2rhel_repo_satellite
...
