---
- name: Convert2RHEL pre-analysis report
  ansible.builtin.shell: >
    export PATH={{ analysis_os_path }};
    set -o pipefail;
    convert2rhel analyze -y
    {{ analysis_convert2rhel_preconv_opts }}
    -c {{ convert2rhel_configfile.path }}
    {{ analysis_convert2rhel_enable_repos_args }}
    {{ analysis_convert2rhel_disable_repos_args }}
    {% if analysis_convert2rhel_eus %}
    --eus
    {% endif %}
    2>&1
  register: convert2rhel
  args:
    executable: /bin/bash
  async: "{{ analysis_async_timeout_maximum | int }}"
  poll: "{{ analysis_async_poll_interval | int }}"
  changed_when: "'Pre-conversion analysis report' not in convert2rhel.stdout"
  notify: Remove temporary configuration file

- name: Notify register to pre convert activation key
  ansible.builtin.assert:
    that: true
    # quiet: true
  changed_when: true
  notify: Register to pre convert activation key
  when:
    - analysis_convert2rhel_repo_type == 'satellite'
    - rhsm_org is defined
    - rhsm_activation_key_pre_convert is defined

- name: Include check-results-file.yml
  ansible.builtin.include_tasks: check-results-file.yml

- name: Include the parse_c2r_report role to check if conversion inhibited
  ansible.builtin.include_role:
    name: infra.convert2rhel.parse_c2r_report

...
