---
# tasks file for analysis
- name: Check distribution and install convert2rhel
  ansible.builtin.import_role:
    name: infra.convert2rhel.common

- name: /etc/ansible/facts.d directory exists
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Capture current ansible_facts for validation after analysis
  ansible.builtin.copy:
    content: "{{ ansible_facts | ansible.builtin.combine({'ansible_local': {}}) }}"
    dest: /etc/ansible/facts.d/pre_convert2rhel.fact
    mode: "0644"
    owner: root
    group: root

- name: Include tasks for convert2rhel pre-conversion analysis
  ansible.builtin.include_tasks: analysis-c2r.yml

- name: Notify analysis report is done handler
  ansible.builtin.assert:
    that: true
    quiet: true
  changed_when: true
  notify: Pre-conversion analysis report is done

- name: Satellite content host - switch back to pre Convert2RHEL lifecycle environment and content view
  when: analysis_convert2rhel_repo_type == 'satellite'
  redhat.satellite.host:
    name: "{{ ansible_host }}"
    lifecycle_environment: "{{ rhsat_lifecycle_environment_pre_convert }}"
    content_view: "{{ rhsat_content_view_pre_convert }}"

...
