---
# tasks file for analysis
- name: Check distribution and install convert2rhel
  ansible.builtin.import_role:
    name: infra.convert2rhel.common

- name: /etc/ansible/facts.d directory exists
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Capture current ansible_facts for validation after analysis
  ansible.builtin.copy:
    content: "{{ ansible_facts | ansible.builtin.combine({'ansible_local': {}}) }}"
    dest: /etc/ansible/facts.d/pre_ripu.fact
    mode: "0644"
    owner: root
    group: root

- name: Register output of 'yum repolist'
  ansible.builtin.shell: >
    export PATH={{ analysis_os_path }};
    set -o pipefail;
    yum repolist all --verbose | grep Repo-baseurl | grep -v convert2rhel
  args:
    executable: /bin/bash
  register: yum_repolist_for_baseurl
  changed_when: yum_repolist_for_baseurl.rc != 0

- name: Set analysis_convert2rhel_repo_type to 'satellite'
  ansible.builtin.set_fact:
    analysis_convert2rhel_repo_type: 'satellite'
  when: yum_repolist_for_baseurl.stdout | regex_search('\/pulp\/content\/' + rhsm_org | string + '\/' + rhsm_activation_key_pre_convert | string )

- name: Include tasks for convert2rhel pre-conversion analysis
  ansible.builtin.include_tasks: analysis-c2r.yml
  # NOTE: I guess this should be extended to more distros
  # NOTE2: Assert for distribution and major.minor version in common role handles this
  # when:
  #   - ansible_distribution == "CentOS" and ansible_distribution_major_version|int == 7

- name: Display pre-conversion registration variables
  ansible.builtin.debug:
    msg:
      analysis_convert2rhel_repo_type: "{{ analysis_convert2rhel_repo_type }}"
      rhsm_org: "{{ rhsm_org }}"
      rhsm_activation_key_pre_convert: "{{ rhsm_activation_key_pre_convert }}"

- name: Notify analysis report is done handler
  ansible.builtin.assert:
    that: true
    # quiet: true
  changed_when: true
  notify: Pre-conversion analysis report is done

- name: Register to pre convert activation key
  community.general.redhat_subscription:
    state: present
    activationkey: "{{ rhsm_activation_key_pre_convert }}"
    org_id: "{{ rhsm_org }}"
    force_register: true
  when:
    - analysis_convert2rhel_repo_type == 'satellite'
    - rhsm_org is defined
    - rhsm_activation_key_pre_convert is defined
...
